#!/bin/bash

backupdir=/home/foundry/foundryuserdata

find $backupdir -mindepth 1 -maxdepth 1 -print0 -type d | xargs -r -0 -I{} /home/foundry/backup {}

rclone sync -u -v -M \
  --check-first \
  --transfers 10 \
  --stats 0 \
  --stats-one-line-date \
  --include "*.tar.?z" \
  --refresh-times \
  /home/foundry/backups onedrive:/FoundryVTT
