#!/bin/bash

folderpath="$1"
foundrydir=/home/foundry/foundryuserdata
backupdir=/home/foundry/backups

if [[ -z "$folderpath" ]] || [[ ! -d $folderpath ]]; then
  echo "Please provide folder to compare"
  exit 1
fi

foldername=$(basename "$folderpath")
backupfoldername="$backupdir/$foldername"

if [[ -r "$backupfoldername.tar.gz" && -w "$backupfoldername.tar.gz" ]]; then
  gzip -d -v "$backupfoldername.tar.gz"
fi

if [[ -r "$backupfoldername.tar" ]]; then
  tar -C $foundrydir -df "$backupfoldername.tar" "$foldername" 1>/dev/null 2>&1
else
  tar -C $foundrydir -cvf "$backupfoldername.tar" "$foldername" --totals
fi

if [[ $? -eq 1 ]]; then
  rm -v "$backupfoldername.tar"
  tar -C $foundrydir -cvf "$backupfoldername.tar" "$foldername" --totals | gzip -n --rsyncable -v
else
  gzip --rsyncable -v "$backupfoldername.tar"
fi
