#!/bin/bash

backupdir=/home/foundry/foundryuserdata

find $backupdir -mindepth 1 -maxdepth 1 -print0 -type d | xargs -r -0 -I{} /home/foundry/backup {}

rclone copy -u -v -M --transfers 10 --include "*.tar.gz" /home/foundry/backups onedrive:/FoundryVTT
